# Generated by Django 4.1 on 2022-12-21 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_review_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
